version: "3.8"
services:
  mysql:
    image: mysql:5.7.32
    container_name: batch-study
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ~/Programs/05.volume/spring-batch:/var/lib/mysql
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --lower_case_table_names=1